import*as THREE from"three";import{OrbitControls}from"three/addons/controls/OrbitControls.js";import{HandLandmarker,FilesetResolver}from"https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.34/vision_bundle.mjs";
const M=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||innerWidth<780,D=new URLSearchParams(location.search).has("debug"),EX=[["Água",962],["Etanol",702],["Benzeno",241],["Cafeína",2519],["Aspirina",2244],["Dopamina",681],["Glicose",5793]],SY={1:"H",6:"C",7:"N",8:"O",9:"F",15:"P",16:"S",17:"Cl",35:"Br",53:"I"},CO={H:"#f5f5f5",C:"#242424",N:"#2f55d4",O:"#e21b23",P:"#ff8a00",S:"#f2c230",Cl:"#34b233",X:"#888"},RA={H:.14,C:.22,N:.21,O:.21,P:.24,S:.24,Cl:.24,X:.22};
const L={241:{cid:241,atoms:[["C",1.396,0,0],["C",.698,1.209,0],["C",-.698,1.209,0],["C",-1.396,0,0],["C",-.698,-1.209,0],["C",.698,-1.209,0],["H",2.479,0,0],["H",1.24,2.147,0],["H",-1.24,2.147,0],["H",-2.479,0,0],["H",-1.24,-2.147,0],["H",1.24,-2.147,0]],bonds:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0],[0,6],[1,7],[2,8],[3,9],[4,10],[5,11]],bo:[2,1,2,1,2,1,1,1,1,1,1,1]}};
const $=x=>document.getElementById(x),cv=$("scene"),ov=$("handOverlay"),cx=ov?.getContext("2d"),vi=$("cameraVideo"),ex=$("examples"),q=$("queryInput"),fo=$("searchForm"),ga=$("galleryMode"),ab=$("arMode"),nm=$("moleculeName"),fm=$("moleculeFormula"),mt=$("moleculeMeta"),lo=$("loading"),lt=$("loadingText"),hs=$("handStatus"),tb=$("toastBox");if(D&&ov)ov.classList.add("visible");
let R=new THREE.WebGLRenderer({canvas:cv,alpha:true,antialias:!M});R.setSize(innerWidth,innerHeight);R.setPixelRatio(Math.min(devicePixelRatio||1,M?1.25:2));R.setClearColor(0xeeeeee,1);let S=new THREE.Scene;S.background=new THREE.Color("#eee");let C=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,100);C.position.z=7;let O=new OrbitControls(C,cv);O.enableDamping=true;O.enablePan=false;O.autoRotate=true;S.add(new THREE.AmbientLight("#fff",1.5));let li=new THREE.DirectionalLight("#fff",1.5);li.position.set(4,6,6);S.add(li);
let G=null,mol=null,ar=0,tr=null,st=null,tim=null,seen=0,found=0,tp=new THREE.Vector3(0,.16,0),tq=new THREE.Quaternion,ts=new THREE.Vector3(.8,.8,.8),eu=new THREE.Euler,ca=new Map;
function msg(s){lt.textContent=s;lo.classList.remove("hidden")}function hid(){lo.classList.add("hidden")}function toast(s,t="info"){let e=document.createElement("div");e.className="toast "+t;e.textContent=s;tb.appendChild(e);requestAnimationFrame(()=>e.classList.add("show"));setTimeout(()=>e.remove(),3600)}function stat(s,k=0){hs.classList.remove("hidden");hs.classList.toggle("detected",k);hs.textContent=s}function bs(){let n=mol?.atoms?.length||12;return n>45?.42:n>25?.5:n>14?.62:.78}
async function ft(u){let c=new AbortController,t=setTimeout(()=>c.abort(),12000);try{return await fetch(u,{signal:c.signal})}finally{clearTimeout(t)}}async function cid(n){let r=await ft("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/"+encodeURIComponent(n)+"/cids/JSON");if(!r.ok)throw 0;return(await r.json()).IdentifierList.CID[0]}async function pub(id){for(let u of [`https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/${id}/record/JSON?record_type=3d`,`https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/${id}/record/JSON?record_type=2d`])try{let c=(await(await ft(u)).json()).PC_Compounds[0],m=parse(c,id);if(m.bonds.length)return m}catch(e){}throw 0}
function parse(c,id){let a=c.atoms.aid||[],el=c.atoms.element||[],co=c.coords?.[0],cf=co.conformers[0],am=new Map,atoms=[],ix=new Map;a.forEach((x,i)=>am.set(x,el[i]));(co.aid||a).forEach((aid,i)=>{let e=SY[am.get(aid)||6]||"X";ix.set(aid,i);atoms.push({el:e,pos:[cf.x[i]||0,cf.y[i]||0,cf.z?.[i]||0]})});let bonds=[],bo=[],b=c.bonds||{};(b.aid1||[]).forEach((x,i)=>{let p=ix.get(x),q=ix.get(b.aid2[i]);if(Number.isInteger(p)&&Number.isInteger(q)){bonds.push([p,q]);bo.push(Math.min(3,Math.max(1,b.order?.[i]||1)))}});return norm({cid:id,atoms,bonds,bo})}
function norm(m){let A=m.atoms.map(a=>Array.isArray(a)?{el:a[0],pos:[a[1],a[2],a[3]]}:a),cen=new THREE.Vector3;A.forEach(a=>cen.add(new THREE.Vector3(...a.pos)));cen.divideScalar(A.length);A.forEach(a=>{a.pos=[a.pos[0]-cen.x,a.pos[1]-cen.y,a.pos[2]-cen.z]});let le=[];m.bonds.forEach(([i,j])=>le.push(new THREE.Vector3(...A[i].pos).distanceTo(new THREE.Vector3(...A[j].pos))));le.sort((a,b)=>a-b);let sc=1/(le[Math.floor(le.length/2)]||1);A.forEach(a=>{a.pos=a.pos.map(x=>x*sc);a.r=RA[a.el]||RA.X});return{...m,atoms:A,formula:form(A)}}function form(A){let c={};A.forEach(a=>c[a.el]=(c[a.el]||0)+1);let o=[];if(c.C){o.push("C"+(c.C>1?c.C:""));delete c.C}if(c.H){o.push("H"+(c.H>1?c.H:""));delete c.H}Object.keys(c).sort().forEach(k=>o.push(k+(c[k]>1?c[k]:"")));return o.join("")}
function build(m){let g=new THREE.Group,bg=new THREE.Group,ag=new THREE.Group;function cyl(a,b,o){let s=new THREE.Vector3(...a.pos),e=new THREE.Vector3(...b.pos),d=e.clone().sub(s),mid=s.clone().add(e).multiplyScalar(.5),mesh=new THREE.Mesh(new THREE.CylinderGeometry(o>1?.032:.052,o>1?.032:.052,d.length(),16),new THREE.MeshPhongMaterial({color:"#8f8f8f"}));mesh.position.copy(mid);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return mesh}m.bonds.forEach(([i,j],k)=>bg.add(cyl(m.atoms[i],m.atoms[j],m.bo[k]||1)));m.atoms.forEach(a=>{let me=new THREE.Mesh(new THREE.SphereGeometry(a.r,32,24),new THREE.MeshPhongMaterial({color:CO[a.el]||CO.X,shininess:80}));me.position.set(...a.pos);ag.add(me)});g.add(bg,ag);return g}
function show(m,n,s="PubChem"){if(G)S.remove(G);mol=m;G=build(m);S.add(G);let box=new THREE.Box3().setFromObject(G),ce=new THREE.Vector3,sz=new THREE.Vector3;box.getCenter(ce);box.getSize(sz);G.position.sub(ce);C.position.z=Math.max(4,Math.min(14,Math.max(sz.x,sz.y,sz.z)*2));O.update();if(ar){let b=bs();tp.set(0,.16,0);ts.set(b,b,b);G.position.copy(tp);G.scale.copy(ts)}nm.textContent=n||"CID "+m.cid;fm.textContent=m.formula;mt.textContent=`${m.atoms.length} átomos · ${m.bonds.length} ligações · ball-and-stick · ${s} CID ${m.cid||""}`}
async function load(id,n){msg("Carregando CID "+id);try{let m=ca.get(id)||await pub(id);ca.set(id,m);hid();show(m,n);toast("Carregado: "+m.formula,"success")}catch{hid();if(L[id])show(norm(L[id]),n,"fallback");else toast("Falha ao carregar","error")}}async function search(x){x=x.trim();if(!x)return;if(/^\d+$/.test(x))return load(+x,"CID "+x);try{msg("Buscando...");let id=await cid(x);hid();load(id,x)}catch{hid();toast("Não encontrado","error")}}
EX.forEach(([n,id])=>{let b=document.createElement("button");b.className="example-button";b.textContent=n;b.onclick=()=>load(id,n);ex.appendChild(b)});fo.onsubmit=e=>{e.preventDefault();search(q.value)};
async function tracker(){if(tr)return tr;let v=await FilesetResolver.forVisionTasks("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.34/wasm");return tr=await HandLandmarker.createFromOptions(v,{baseOptions:{modelAssetPath:"https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task",delegate:"CPU"},runningMode:"VIDEO",numHands:1,minHandDetectionConfidence:.2,minHandPresenceConfidence:.2,minTrackingConfidence:.2})}
async function start(){try{msg("Iniciando câmera e mão...");await tracker();st=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:"user",width:{ideal:M?320:640},height:{ideal:M?240:480}}});vi.srcObject=st;await vi.play();vi.classList.add("ar-visible");S.background=null;R.setClearColor(0,0);ar=1;O.enabled=false;O.autoRotate=false;let b=bs();tp.set(0,.16,0);ts.set(b,b,b);if(G){G.position.copy(tp);G.scale.copy(ts)}ga.classList.remove("active");ab.classList.add("active");stat("Mostre a mão aberta ou use toque",0);tim=setInterval(detect,M?140:100);hid()}catch(e){hid();toast("AR falhou: "+(e.message||e),"error")}}
function stop(){clearInterval(tim);st?.getTracks().forEach(t=>t.stop());vi.srcObject=null;vi.classList.remove("ar-visible");S.background=new THREE.Color("#eee");R.setClearColor(0xeeeeee,1);ar=0;O.enabled=true;O.autoRotate=true;ga.classList.add("active");ab.classList.remove("active");hs.classList.add("hidden")}ga.onclick=stop;ab.onclick=start;
function detect(){if(!ar||!tr||vi.readyState<2)return;let r=tr.detectForVideo(vi,performance.now()),h=r?.landmarks?.[0];if(!h){found=0;if(performance.now()-seen>900)stat("Mostre a mão aberta ou use toque",0);return}found=1;seen=performance.now();stat("Mão detectada — gire/incline",1);let w=h[0],i=h[5],m=h[9],p=h[17],cx=(w.x+i.x+m.x+p.x)/4,cy=(w.y+i.y+m.y+p.y)/4;eu.set((cy-.5)*Math.PI*.9,(.5-cx)*Math.PI*1.35,-Math.atan2(i.y-p.y,i.x-p.x));tq.setFromEuler(eu);tp.set(0,.16,0);let val=Math.min(1,Math.max(0,Math.hypot(m.x-w.x,m.y-w.y)*4)),b=bs(),s=b*(.85+val*.35);ts.set(s,s,s);if(D&&ctx){let W=innerWidth,H=innerHeight;ov.width=W;ov.height=H;ctx.clearRect(0,0,W,H);ctx.fillStyle="white";h.forEach(P=>{ctx.beginPath();ctx.arc((1-P.x)*W,P.y*H,4,0,7);ctx.fill()})}}
cv.addEventListener("touchmove",e=>{if(!ar||!G)return;e.preventDefault();if(e.touches.length===1){ry+=e.movementX||0;eu.set(e.touches[0].clientY/innerHeight-.5,e.touches[0].clientX/innerWidth-.5,0);tq.setFromEuler(eu)}},{passive:false});
function anim(){requestAnimationFrame(anim);if(G){if(ar){G.position.lerp(tp,.16);G.quaternion.slerp(tq,.14);G.scale.lerp(ts,.14)}else G.rotation.y+=.0004}O.update();R.render(S,C)}addEventListener("resize",()=>{C.aspect=innerWidth/innerHeight;C.updateProjectionMatrix();R.setSize(innerWidth,innerHeight)});anim();load(241,"Benzeno");
